name = "JuliassicPark"
uuid = "f1e977c7-1234-4567-b89a-aabbccddeeff"
version = "0.1.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Margins = "883ce5cb-1d42-4db9-84e7-eea888f0a17e"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ADTypes = "1.18.0"
ArgParse = "1.2.0"
BenchmarkTools = "1.6.0"
CSV = "0.10.15"
DataFrames = "1.7.0"
Distributed = "1.11.0"
Distributions = "0.25.120"
ForwardDiff = "1.1.0"
IterTools = "1.10.0"
LaTeXStrings = "1.4.0"
Margins = "2.0.2"
NLsolve = "4.5.1"
NaNMath = "1.1.3"
NonlinearSolve = "4.12.0"
Optim = "1.13.2"
PProf = "3.2.0"
PreallocationTools = "0.4.34"
ProfileView = "1.10.1"
ProgressMeter = "1.10.4"
Random = "1.11.0"
Revise = "3.8.0"
SplitApplyCombine = "1.2.3"
StatsBase = "0.34.5"
Tables = "1.12.1"
Test = "1.11.0"
julia = "1.9"
